name: soil_vm_flutter
repository: https://github.com/MarcelGarus/soil
publish_to: none

environment:
  flutter: ^3.22.0
  sdk: ^3.4.0

dependencies:
  file_picker: ^8.0.3
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  soil_vm:
    path: ../dart
  supernova_flutter:
    git:
      url: https://github.com/JonasWanke/supernova.git
      path: supernova_flutter
      ref: c568672838f2982d0b04562f33b42f6bafa85f70

dependency_overrides:
  supernova:
    git:
      url: https://github.com/JonasWanke/supernova.git
      path: supernova
      ref: c568672838f2982d0b04562f33b42f6bafa85f70

flutter:
  uses-material-design: true
